@startuml
object Sender {
    Encrypt data
}
package payload {
    object Contents{
        Length Of encrypted DEK (Int32)
        Asymmemetric Encrypted DEK(Data Encryption Key)  
        Length Of encrypted IV (Int32)
        Asymmemetric Encrypted IV (Initialization Vector)
        Symmetric Encrypted Data using DEK
    }
}
object Receiver {
    Decrypt data
}
Sender -right-> Contents
Contents -right-> Receiver
@enduml
